transformed_no_boupr_another_kpp = {
    "form1": [
        {
            "code": "1150",
            "name": "Материальные внеоборотные активы ",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1170",
            "name": "Нематериальные, финансовые и другие внеоборотные активы",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1210",
            "name": "Запасы",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1230",
            "name": "Финансовые и другие оборотные активы",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1250",
            "name": "Денежные средства и денежные эквиваленты",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1300",
            "name": "Итого по разделу III",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1300",
            "name": "Фонд недвижимого и особо ценного движимого имущества и иные целевые фонды",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1300",
            "name": "Целевые средства",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1410",
            "name": "Долгосрочные заемные средства",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1450",
            "name": "Другие долгосрочные обязательства",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1510",
            "name": "Краткосрочные заемные средства",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1520",
            "name": "Кредиторская задолженность",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1550",
            "name": "Другие краткосрочные обязательства",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1600",
            "name": "БАЛАНС",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "1700",
            "name": "БАЛАНС",
            "startValue": 200,
            "endValue": 200,
        },
    ],
    "form2": [
        {
            "code": "2110",
            "name": "Выручка за минусом налога на добавленную стоимость, акцизов",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "2120",
            "name": "Расходы по обычной деятельности",
            "startValue": -200,
            "endValue": -200,
        },
        {
            "code": "2330",
            "name": "Проценты к уплате",
            "startValue": -200,
            "endValue": -200,
        },
        {
            "code": "2340",
            "name": "Прочие доходы",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "2350",
            "name": "Прочие расходы",
            "startValue": -200,
            "endValue": -200,
        },
        {
            "code": "2400",
            "name": "Чистая прибыль (убыток)",
            "startValue": 200,
            "endValue": 200,
        },
        {
            "code": "2410",
            "name": "Налоги на прибыль (доходы)",
            "startValue": -200,
            "endValue": -200,
        },
    ],
}
