transformed_no_buhotch_special = {
    "form1": [
        {
            "code": "1100",
            "name": "Итого по разделу I",
            "startValue": 72158,
            "endValue": 71932,
        },
        {
            "code": "1150",
            "name": "Основные средства",
            "startValue": 62489,
            "endValue": 61595,
        },
        {
            "code": "1180",
            "name": "Отложенные налоговые активы",
            "startValue": 9669,
            "endValue": 10337,
        },
        {
            "code": "1200",
            "name": "Итого по разделу II",
            "startValue": 3079,
            "endValue": 1906,
        },
        {
            "code": "1210",
            "name": "Запасы",
            "startValue": 1044,
            "endValue": 632,
        },
        {
            "code": "1220",
            "name": "Налог на добавленную стоимость по приобретенным ценностям",
            "startValue": 49,
            "endValue": 153,
        },
        {
            "code": "1230",
            "name": "Дебиторская задолженность",
            "startValue": 636,
            "endValue": 996,
        },
        {
            "code": "1250",
            "name": "Денежные средства и денежные эквиваленты",
            "startValue": 1350,
            "endValue": 125,
        },
        {
            "code": "1300",
            "name": "Итого по разделу III",
            "startValue": 65726,
            "endValue": 62531,
        },
        {
            "code": "1310",
            "name": "Уставный капитал (складочный капитал, уставный фонд, вклады товарищей)",
            "startValue": 71503,
            "endValue": 71503,
        },
        {
            "code": "1350",
            "name": "Добавочный капитал (без переоценки)",
            "startValue": 36065,
            "endValue": 36065,
        },
        {
            "code": "1370",
            "name": "Нераспределенная прибыль (непокрытый убыток)",
            "startValue": -41842,
            "endValue": -45037,
        },
        {
            "code": "1400",
            "name": "Итого по разделу IV",
            "startValue": 1884,
            "endValue": 2311,
        },
        {
            "code": "1420",
            "name": "Отложенные налоговые обязательства",
            "startValue": 1884,
            "endValue": 2311,
        },
        {
            "code": "1500",
            "name": "Итого по разделу V",
            "startValue": 7627,
            "endValue": 8996,
        },
        {
            "code": "1520",
            "name": "Кредиторская задолженность",
            "startValue": 7627,
            "endValue": 8996,
        },
        {
            "code": "1600",
            "name": "БАЛАНС",
            "startValue": 75237,
            "endValue": 73838,
        },
        {
            "code": "1700",
            "name": "БАЛАНС",
            "startValue": 75237,
            "endValue": 73838,
        },
    ],
    "form2": [
        {
            "code": "2100",
            "name": "Валовая прибыль (убыток)",
            "startValue": -16586,
            "endValue": -19592,
        },
        {
            "code": "2110",
            "name": "Выручка за минусом налога на добавленную стоимость, акцизов",
            "startValue": 27648,
            "endValue": 28162,
        },
        {
            "code": "2120",
            "name": "Себестоимость продаж",
            "startValue": -44234,
            "endValue": -47754,
        },
        {
            "code": "2200",
            "name": "Прибыль (убыток) от продаж",
            "startValue": -16586,
            "endValue": -19592,
        },
        {
            "code": "2300",
            "name": "Прибыль (убыток) до налогообложения",
            "startValue": 11628,
            "endValue": -2032,
        },
        {
            "code": "2340",
            "name": "Прочие доходы",
            "startValue": 37009,
            "endValue": 22223,
        },
        {
            "code": "2350",
            "name": "Прочие расходы",
            "startValue": -8795,
            "endValue": -4663,
        },
        {
            "code": "2400",
            "name": "Чистая прибыль (убыток)",
            "startValue": 8301,
            "endValue": -1791,
        },
        {
            "code": "2410",
            "name": "Налог на прибыль",
            "startValue": 629,
            "endValue": 241,
        },
        {
            "code": "2411",
            "name": "Текущий налог на прибыль",
            "startValue": 0,
            "endValue": 0,
        },
        {
            "code": "2412",
            "name": "Отложенный налог на прибыль",
            "startValue": 629,
            "endValue": 241,
        },
        {
            "code": "2421",
            "name": "в т.ч. постоянные налоговые обязательства (активы)",
            "startValue": -1001,
            "endValue": -166,
        },
        {
            "code": "2430",
            "name": "Изменение отложенных налоговых обязательств",
            "startValue": -484,
            "endValue": -427,
        },
        {
            "code": "2450",
            "name": "Изменение отложенных налоговых активов",
            "startValue": 1113,
            "endValue": 668,
        },
        {
            "code": "2460",
            "name": "Прочее",
            "startValue": -3956,
            "endValue": 0,
        },
        {
            "code": "2500",
            "name": "Совокупный финансовый результат периода",
            "startValue": 8301,
            "endValue": -1791,
        },
    ],
}
