transformed_no_buhotch = {
    "form1": [
        {
            "code": "1100",
            "name": "Итого по разделу I",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1110",
            "name": "Нематериальные активы",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1120",
            "name": "Результаты исследований и разработок",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1130",
            "name": "Нематериальные поисковые активы",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1140",
            "name": "Материальные поисковые активы",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1150",
            "name": "Основные средства",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1160",
            "name": "Доходные вложения в материальные ценности",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1170",
            "name": "Финансовые вложения",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1180",
            "name": "Отложенные налоговые активы",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1190",
            "name": "Прочие внеоборотные активы",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1200",
            "name": "Итого по разделу II",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1210",
            "name": "Запасы",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1220",
            "name": "Налог на добавленную стоимость по приобретенным ценностям",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1230",
            "name": "Дебиторская задолженность",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1240",
            "name": "Финансовые вложения (за исключением денежных эквивалентов)",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1250",
            "name": "Денежные средства и денежные эквиваленты",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1260",
            "name": "Прочие оборотные активы",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1300",
            "name": "Итого по разделу III",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1300",
            "name": "Итого по разделу III",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1310",
            "name": "Паевой фонд",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1310",
            "name": "Уставный капитал (складочный капитал, уставный фонд, вклады товарищей)",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1320",
            "name": "Собственные акции, выкупленные у акционеров",
            "startValue": -100,
            "endValue": -100,
        },
        {
            "code": "1320",
            "name": "Целевой капитал",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1340",
            "name": "Переоценка внеоборотных активов",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1350",
            "name": "Добавочный капитал (без переоценки)",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1350",
            "name": "Целевые средства",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1360",
            "name": "Резервный капитал",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1360",
            "name": "Фонд недвижимого и особо ценного движимого имущества",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1370",
            "name": "Нераспределенная прибыль (непокрытый убыток)",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1370",
            "name": "Резервный и иные целевые фонды",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1400",
            "name": "Итого по разделу IV",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1410",
            "name": "Заемные средства",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1420",
            "name": "Отложенные налоговые обязательства",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1430",
            "name": "Оценочные обязательства",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1450",
            "name": "Прочие обязательства",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1500",
            "name": "Итого по разделу V",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1510",
            "name": "Заемные средства",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1520",
            "name": "Кредиторская задолженность",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1530",
            "name": "Доходы будущих периодов",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1540",
            "name": "Оценочные обязательства",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1550",
            "name": "Прочие обязательства",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1600",
            "name": "БАЛАНС",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "1700",
            "name": "БАЛАНС",
            "startValue": 100,
            "endValue": 100,
        },
    ],
    "form2": [
        {
            "code": "2100",
            "name": "Валовая прибыль (убыток)",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2110",
            "name": "Выручка за минусом налога на добавленную стоимость, акцизов",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2120",
            "name": "Себестоимость продаж",
            "startValue": -100,
            "endValue": -100,
        },
        {
            "code": "2200",
            "name": "Прибыль (убыток) от продаж",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2210",
            "name": "Коммерческие расходы",
            "startValue": -100,
            "endValue": -100,
        },
        {
            "code": "2220",
            "name": "Управленческие расходы",
            "startValue": -100,
            "endValue": -100,
        },
        {
            "code": "2300",
            "name": "Прибыль (убыток) до налогообложения",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2310",
            "name": "Доходы от участия в других организациях",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2320",
            "name": "Проценты к получению",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2330",
            "name": "Проценты к уплате",
            "startValue": -100,
            "endValue": -100,
        },
        {
            "code": "2340",
            "name": "Прочие доходы",
            "startValue": 100,
            "endValue": 100
        },
        {
            "code": "2350",
            "name": "Прочие расходы",
            "startValue": -100,
            "endValue": -100,
        },
        {
            "code": "2400",
            "name": "Чистая прибыль (убыток)",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2410",
            "name": "Налог на прибыль",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2411",
            "name": "Текущий налог на прибыль",
            "startValue": -100,
            "endValue": -100,
        },
        {
            "code": "2412",
            "name": "Отложенный налог на прибыль",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2421",
            "name": "в т.ч. постоянные налоговые обязательства (активы)",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2430",
            "name": "Изменение отложенных налоговых обязательств",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2450",
            "name": "Изменение отложенных налоговых активов",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2460",
            "name": "Прочее",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2500",
            "name": "Совокупный финансовый результат периода",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2510",
            "name": "Результат от переоценки внеоборотных активов, не включаемый в чистую прибыль (убыток) периода",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2520",
            "name": "Результат от прочих операций, не включаемый в чистую прибыль (убыток) периода",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2530",
            "name": "Налог на прибыль от операций, результат которых не включается в чистую прибыль (убыток) периода",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2900",
            "name": "Базовая прибыль (убыток) на акцию",
            "startValue": 100,
            "endValue": 100,
        },
        {
            "code": "2910",
            "name": "Разводненная прибыль (убыток) на акцию",
            "startValue": 100,
            "endValue": 100,
        },
    ],
}
