# Generated by Django 2.2.19 on 2021-04-06 13:12

import django.db.models.deletion
from django.db import migrations, models

import bfo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования')),
                ('report_date', models.DateField(verbose_name='Дата отчёта')),
                ('data_from_src', django.db.models.JSONField(blank=True, default=None, null=True, verbose_name='Значения финансовых показателей')),
                ('inn', models.CharField(blank=True, max_length=10, null=True, verbose_name='ИНН организации')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП организации')),
            ],
            options={
                'verbose_name': 'Значения финансовых показателей по организациям',
                'verbose_name_plural': 'Значения финансовых показателей по организациям',
            },
        ),
        migrations.CreateModel(
            name='PreviousOrgStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования')),
                ('report_date', models.DateField(verbose_name='Дата отчёта')),
                ('data_from_src', django.db.models.JSONField(blank=True, default=None, null=True, verbose_name='Значения финансовых показателей')),
                ('inn', models.CharField(blank=True, max_length=10, null=True, verbose_name='ИНН организации')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП организации')),
            ],
            options={
                'verbose_name': 'Устаревшие значения финансовых показателей по организациям',
                'verbose_name_plural': 'Устаревшие значения финансовых показателей по организациям',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования')),
                ('base_url', models.CharField(default=bfo.models.base_url_setting_default_value, max_length=500, verbose_name='URL для скачивания')),
                ('last_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата последнего успешного сохранения данных в таблицу bfo_orgstatement')),
                ('username', models.CharField(blank=True, max_length=128, null=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль (зашифрованный)')),
            ],
            options={
                'verbose_name': 'Настройки загрузки финансовых показателей',
                'verbose_name_plural': 'Настройки загрузки финансовых показателей',
            },
        ),
        migrations.CreateModel(
            name='StatementForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования')),
                ('form_name', models.CharField(max_length=255, verbose_name='Наименование формы')),
            ],
            options={
                'verbose_name': 'Форма отчетности',
                'verbose_name_plural': 'Формы отчетности',
            },
        ),
        migrations.CreateModel(
            name='StatementDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования')),
                ('title', models.CharField(max_length=500, verbose_name='Название показателя')),
                ('code', models.CharField(blank=True, max_length=4, null=True, verbose_name='Код')),
                ('ext_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название параметра, пришедшего из ГИР БО')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfo.StatementForm', verbose_name='Форма отчетности')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='bfo.StatementDictionary', verbose_name='Родительский финансовый показатель')),
            ],
            options={
                'verbose_name': 'Справочник финансовых показателей',
                'verbose_name_plural': 'Справочники финансовых показателей',
            },
        ),
        migrations.CreateModel(
            name='DifferenceStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff', django.db.models.JSONField(blank=True, default=None, null=True, verbose_name='Разница')),
                ('org_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfo.OrgStatement', verbose_name='Актуальные значения финансовых показателей')),
                ('previous_org_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfo.PreviousOrgStatement', verbose_name='Устаревшие значения финансовых показателей')),
            ],
            options={
                'verbose_name': 'Разница актуальных и устаревших значений финансовых показателей',
                'verbose_name_plural': 'Разница актуальных и устаревших значений финансовых показателей',
            },
        ),
    ]
