# Generated by Django 2.2.19 on 2021-04-06 13:16

from django.contrib.auth.hashers import make_password
from django.db import migrations


def forward(apps, schema_editor):
    User = apps.get_registered_model('auth', 'User')
    User.objects.all().delete()
    User.objects.create(
        username='root',
        email='pivovarov_av@srvhub.ru',
        password=make_password('root'),
        is_superuser=True,
        is_staff=True
    )
    Setting = apps.get_registered_model('bfo', 'Setting')
    Setting.objects.create()


def backward(apps, schema_editor):
    User = apps.get_registered_model('auth', 'User')
    User.objects.filter(username='root').delete()
    settings = apps.get_registered_model('rsmp', 'Setting')
    settings.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('bfo', '0002_fill_dictionary_and_form'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
