# Generated by Django 2.2.24 on 2021-06-30 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bfo', '0003_create_superuser_and_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatementPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования')),
                ('year', models.IntegerField(default=1, verbose_name='Год')),
                ('page', models.IntegerField(default=1, verbose_name='Номер страницы')),
                ('total_pages', models.IntegerField(default=1, verbose_name='Общее количество страниц')),
                ('size', models.IntegerField(default=1, verbose_name='Количество записей на странице')),
                ('sort', models.CharField(max_length=100, verbose_name='Параметры сортировки')),
                ('params', django.db.models.JSONField(verbose_name='Параметры запроса')),
            ],
            options={
                'verbose_name': 'Страница финансовой отчетности',
                'verbose_name_plural': 'Страницы финансовой отчетности',
            },
        ),
        migrations.AddField(
            model_name='differencestatement',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования'),
        ),
        migrations.AddField(
            model_name='differencestatement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now,
                                       verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='orgstatement',
            index_together={('inn', 'kpp')},
        ),
        migrations.AlterIndexTogether(
            name='previousorgstatement',
            index_together={('inn', 'kpp')},
        ),
        migrations.CreateModel(
            name='FinancialStatementFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования')),
                ('external_id', models.IntegerField(verbose_name='ID на ГИРБО')),
                ('token', models.CharField(max_length=50, verbose_name='Токен')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('file_name', models.CharField(max_length=500, verbose_name='Название файла')),
                ('report_type', models.CharField(max_length=50, verbose_name='Тип отчёта')),
                ('period', models.CharField(max_length=4, verbose_name='Отчётный период')),
                ('upload_date', models.DateField(verbose_name='Дата представления файла')),
                ('is_downloaded', models.BooleanField(default=False, verbose_name='Файл загружен и обработан')),
                ('downloaded_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files',
                                                      to='bfo.FinancialStatementPage',
                                                      verbose_name='Страница внутри фин. показателей.')),
            ],
            options={
                'verbose_name': 'Файл финансовой отчетности',
                'verbose_name_plural': 'Файлы финансовой отчетности',
            },
        ),
        migrations.AddField(
            model_name='orgstatement',
            name='statement_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='bfo.FinancialStatementFile',
                                    verbose_name='Актуальные значения финансовых показателей'),
        ),
        migrations.AddField(
            model_name='previousorgstatement',
            name='statement_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='bfo.FinancialStatementFile',
                                    verbose_name='Актуальные значения финансовых показателей'),
        ),
        migrations.AddIndex(
            model_name='financialstatementfile',
            index=models.Index(fields=['inn'], name='bfo_financi_inn_58f932_idx'),
        ),
    ]
