# Generated by Django 2.2.24 on 2021-07-08 11:00

from django.db import migrations


def forward(apps, schema_editor):
    StatementDictionary = apps.get_model('bfo', 'StatementDictionary')
    StatementDictionary.objects.filter(title='Капитал и резервы', form_id=1, code=1300, ext_name='КапРез').delete()


def backward(apps, schema_editor):
    StatementDictionary = apps.get_model('bfo', 'StatementDictionary')
    StatementDictionary.objects.create(
        title='Капитал и резервы',
        form_id=1,
        code=1300,
        ext_name='КапРез',
        parent_id=43,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('bfo', '0004_page_and_files_models'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
