# Generated by Django 2.2.24 on 2021-07-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfo', '0005_delete_statement_dictionary_object'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='financialstatementfile',
            index=models.Index(fields=['token'], name='bfo_financi_token_160265_idx'),
        ),
    ]
