# Generated by Django 2.2.24 on 2021-07-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfo', '0006_add_index_for_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatementfile',
            name='token',
            field=models.CharField(max_length=50, unique=True, verbose_name='Токен'),
        ),
    ]
