# Generated by Django 2.2.24 on 2021-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfo', '0007_auto_20210723_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatementpage',
            name='actual_size',
            field=models.IntegerField(default=100, verbose_name='Фактическое количество элементов на странице'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialstatementpage',
            name='page',
            field=models.IntegerField(verbose_name='Номер страницы'),
        ),
        migrations.AlterField(
            model_name='financialstatementpage',
            name='size',
            field=models.IntegerField(verbose_name='Количество записей на странице'),
        ),
        migrations.AlterField(
            model_name='financialstatementpage',
            name='sort',
            field=models.CharField(max_length=255, verbose_name='Параметры сортировки'),
        ),
        migrations.AlterField(
            model_name='financialstatementpage',
            name='total_pages',
            field=models.IntegerField(verbose_name='Общее количество страниц'),
        ),
        migrations.AlterField(
            model_name='financialstatementpage',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
