# Generated by Django 2.2.24 on 2021-08-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfo', '0008_auto_20210723_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryINN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время редактирования')),
                ('inn', models.CharField(blank=True, max_length=10, null=True, verbose_name='ИНН организации')),
                ('statement_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bfo.FinancialStatementFile', verbose_name='Актуальные значения финансовых показателей')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
