# Generated by Django 2.2.24 on 2021-09-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfo', '0011_auto_20210910_1048'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='financialreportfile',
            constraint=models.UniqueConstraint(fields=('ogrn', 'year'), name='ogrn_year_unique'),
        ),
    ]
