# Generated by Django 3.2.8 on 2021-11-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfo', '0012_auto_20210910_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreportfile',
            name='inn',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='ИНН организации'),
        ),
        migrations.AddField(
            model_name='financialreportfile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Файл актуален'),
        ),
    ]
