# Generated by Django 3.2.8 on 2021-11-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bfo', '0013_auto_20211110_1109'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financialreportfile',
            name='ogrn_year_unique',
        ),
        migrations.AlterIndexTogether(
            name='financialreportfile',
            index_together={('ogrn', 'year', 'is_active')},
        ),
        migrations.AddConstraint(
            model_name='financialreportfile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('ogrn', 'year', 'is_active'), name='ogrn_year_is_active_unique'),
        ),
    ]
